select * from EMP;
select * from DEPT;

-- EXERCICE 1

SELECT DEPTNO, ENAME, SAL, rank() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) as "RANG"
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO = 30;


SELECT DEPTNO, ENAME, SAL, dense_rank() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) as "RANG"
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO = 30;

SELECT DISTINCT DEPTNO, SAL, dense_rank() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) as "RANG"
FROM EMP
WHERE DEPTNO = 10 OR DEPTNO = 20
ORDER BY DEPTNO, SAL DESC;

SELECT JOB, SUM(SAL) AS "TOT_SAL_JOB"
FROM EMP
GROUP BY JOB;

SELECT DISTINCT JOB, SUM(SAL) OVER (PARTITION BY JOB) AS "TOT_SAL_JOB"
FROM EMP;

SELECT DISTINCT JOB, (SELECT SUM(SAL) FROM EMP E2 WHERE E1.JOB = E2.JOB) AS "TOT_SAL_JOB"
FROM EMP E1;

-- Le partition by est execut� apr�s que le select soit fait

SELECT DEPTNO, JOB, SUM(SAL)
FROM EMP
GROUP BY ROLLUP (DEPTNO, JOB)
ORDER BY DEPTNO, SUM(SAL);

SELECT NVL(TO_CHAR(DEPTNO), 'TousDep') AS DEPARTEMENT, NVL(TO_CHAR(JOB), 'TousEmployes') AS JOB, SUM(SAL)
FROM EMP
GROUP BY ROLLUP (DEPTNO, JOB)
ORDER BY DEPTNO, SUM(SAL) DESC;

-- Tous d�partement et job confondu => La somme totale tout en bas
-- Par d�partement => rollup avec la somme par departement tout les null apr�s chaque fin de d�partement
-- Par d�partement et job c'est les sommes a droit de chaque ligne de job

SELECT DECODE(DEPTNO, NULL, 'TousDep', DEPTNO) AS DEPARTEMENT, DECODE(JOB, NULL, 'TousEmployes', JOB) AS JOB, SUM(SAL)
FROM EMP
GROUP BY ROLLUP (DEPTNO, JOB)
ORDER BY DEPTNO, SUM(SAL) DESC;

-- EXERCICE 2
select * from clients;
select * from produits;
select * from temps;
select * from ventes;

-- 1
SELECT ANNEE, CL_R, CATEGORY, AVG(QTE * PU) AS CA_MOYEN
FROM VENTES
JOIN CLIENTS ON CLIENTS.CL_ID = VENTES.CID
JOIN PRODUITS ON VENTES.PID = PRODUITS.PID
JOIN TEMPS ON VENTES.TID = TEMPS.TID
WHERE ANNEE = 2009 OR ANNEE = 2010
group by rollup (ANNEE, CL_R, CATEGORY);

-- 2
SELECT ANNEE, CL_R, CATEGORY, AVG(QTE * PU) AS CA_MOYEN
FROM VENTES
JOIN CLIENTS ON CLIENTS.CL_ID = VENTES.CID
JOIN PRODUITS ON VENTES.PID = PRODUITS.PID
JOIN TEMPS ON VENTES.TID = TEMPS.TID
WHERE ANNEE = 2009 OR ANNEE = 2010
group by CUBE (ANNEE, CL_R, CATEGORY);

-- 3
SELECT ANNEE, CATEGORY, PNAME FROM (SELECT t.ANNEE, p.CATEGORY, p.PNAME, RANK() OVER (PARTITION BY t.ANNEE, p.CATEGORY ORDER BY SUM(QTE*PU) DESC) RANG
FROM VENTES v
JOIN PRODUITS p ON v.PID = p.PID
JOIN TEMPS t ON v.TID = t.TID
group by t.ANNEE, p.CATEGORY, p.PNAME)
WHERE RANG = 1;

-- 4
SELECT t.ANNEE, p.CATEGORY, SUM(QTE*PU) AS CA_TOTAL
FROM VENTES v
JOIN PRODUITS p ON v.PID = p.PID
JOIN TEMPS t ON v.TID = t.TID
group by rollup (t.ANNEE, p.CATEGORY)
having GROUPING_ID(t.annee, p.category) != 3
ORDER BY t.ANNEE, CA_TOTAL DESC;

-- 5
SELECT ANNEE, MOIS, CA_TOTAL
FROM (
  SELECT t.ANNEE, t.MOIS, p.PNAME, SUM(QTE*PU) AS CA_TOTAL, rank() OVER (PARTITION BY t.ANNEE ORDER BY SUM(QTE*PU) DESC) AS RANG
  FROM VENTES v
  JOIN PRODUITS p ON v.PID = p.PID
  JOIN TEMPS t ON v.TID = t.TID
  WHERE p.PNAME LIKE 'Sirop d �rable'
  GROUP BY t.ANNEE, t.MOIS, p.PNAME
  ORDER BY t.ANNEE, t.MOIS
  )
WHERE RANG = 1;

-- 6
SELECT t.ANNEE, c.CL_NAME, p.CATEGORY, SUM(QTE*PU) AS CA_TOTAL
FROM VENTES v
JOIN CLIENTS c ON c.CL_ID = v.CID
JOIN PRODUITS p ON v.PID = p.PID
JOIN TEMPS t ON v.TID = t.TID
GROUP BY GROUPING SETS ((t.ANNEE, c.CL_NAME), (t.ANNEE, p.CATEGORY));

-- 7
SELECT p.CATEGORY, SUM(QTE) AS QTE_VENDU_2010, NTILE(3) OVER (ORDER BY SUM(QTE) DESC) AS TIERS
FROM VENTES v
JOIN PRODUITS p ON v.PID = p.PID
JOIN TEMPS t ON v.TID = t.TID
WHERE t.ANNEE = 2010
GROUP BY p.CATEGORY;

-- 8
 SELECT CATEGORY, MOIS, min(TID) as JOUR1, max(TID) as JOUR5, SUM(QTE_JOURS) AS QTE_5_JOURS
 FROM (SELECT p.CATEGORY, sum(QTE) as QTE_JOURS, t.MOIS, t.JOUR, t.TID, dense_rank() OVER (PARTITION BY p.CATEGORY, t.MOIS ORDER BY t.JOUR) AS RANG
  FROM VENTES v
  JOIN PRODUITS p ON v.PID = p.PID
  JOIN TEMPS t ON v.TID = t.TID
  WHERE t.ANNEE = 2010
  GROUP BY t.MOIS, p.CATEGORY, t.JOUR, t.TID)
WHERE RANG BETWEEN 1 AND 5
GROUP BY CATEGORY, MOIS
HAVING count(RANG) = 5
ORDER BY CATEGORY, MOIS;
