select * from clients;
select * from produits;
select * from temps;
select * from ventes;

SELECT ANNEE, CL_R, CATEGORY, AVG(QTE * PU) AS CA_MOYEN 
FROM VENTES
JOIN CLIENTS ON CLIENTS.CL_ID = VENTES.CID
JOIN PRODUITS ON VENTES.PID = PRODUITS.PID
JOIN TEMPS ON VENTES.TID = TEMPS.TID
WHERE ANNEE = 2009 OR ANNEE = 2010
group by rollup (ANNEE, CL_R, CATEGORY);

SELECT ANNEE, CL_R, CATEGORY, AVG(QTE * PU) AS CA_MOYEN 
FROM VENTES
JOIN CLIENTS ON CLIENTS.CL_ID = VENTES.CID
JOIN PRODUITS ON VENTES.PID = PRODUITS.PID
JOIN TEMPS ON VENTES.TID = TEMPS.TID
WHERE ANNEE = 2009 OR ANNEE = 2010
group by CUBE (ANNEE, CL_R, CATEGORY);
--
SELECT (SELECT t.ANNEE, p.CATEGORY, p.PNAME, RANK() OVER (PARTITION BY t.ANNEE ORDER BY SUM(QTE*PU) DESC) rang
FROM VENTES v
JOIN CLIENTS c ON c.CL_ID = v.CID
JOIN PRODUITS p ON v.PID = p.PID
JOIN TEMPS t ON v.TID = t.TID
group by rollup (t.ANNEE, p.CATEGORY, p.PNAME))
FROM VENTES
WHERE rang = 1;
